package vistas;

import controladores.ControladorServicios;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelos.Servicio;

/**
 *
 * @author KENNEDY
 */
public class PanelTiempo extends javax.swing.JPanel {
    private ControladorServicios controladorServicios;
    private DefaultTableModel modeloTabla;
    
    public PanelTiempo(ControladorServicios controladorServicios) {
        initComponents();
        this.controladorServicios = controladorServicios;

    modeloTabla = new DefaultTableModel();
    modeloTabla.addColumn("ID Servicio");
    modeloTabla.addColumn("Cliente");
    modeloTabla.addColumn("Auto");
    modeloTabla.addColumn("Servicio");
    modeloTabla.addColumn("Hora Entrada");
    modeloTabla.addColumn("Hora Salida");
    modeloTabla.addColumn("Duración");

    jTable1.setModel(modeloTabla);

    jTextField2.setEditable(false);
    jTextField3.setEditable(false);
    jTextField4.setEditable(false);

    cargarServicios();
    mostrarTablaTiempo();
}
        
    
private void cargarServicios() {
    jComboBox1.removeAllItems();

    jComboBox1.addItem("Seleccione un servicio");

    for (int i = 0; i < controladorServicios.getContadorServicios(); i++) {
        Servicio servicio = controladorServicios.obtenerServicio(i);

        jComboBox1.addItem(
                servicio.getIdServicio() + " - "
                + servicio.getAuto().getCliente().getNombreCompleto() + " - "
                + servicio.getTipoServicio()
        );
    }
}

private void mostrarDatosServicio() {
    if (jComboBox1.getSelectedItem() == null) {
        return;
    }

    if (jComboBox1.getSelectedIndex() == 0) {
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        return;
    }

    String seleccionado = jComboBox1.getSelectedItem().toString();
    String idServicio = seleccionado.substring(0, seleccionado.indexOf(" - "));

    Servicio servicio = controladorServicios.buscarServicioPorId(idServicio);

    if (servicio != null) {
        jTextField2.setText(servicio.getHoraEntrada());
        jTextField3.setText(servicio.getHoraSalida());
        jTextField4.setText(servicio.getDuracion());
    }
}

private void registrarSalida() {
    if (jComboBox1.getSelectedIndex() == 0) {
        JOptionPane.showMessageDialog(this, "Debes seleccionar un servicio");
        return;
    }

    String seleccionado = jComboBox1.getSelectedItem().toString();
    String idServicio = seleccionado.substring(0, seleccionado.indexOf(" - "));

    Servicio servicio = controladorServicios.buscarServicioPorId(idServicio);

    if (servicio == null) {
        JOptionPane.showMessageDialog(this, "No se encontró el servicio");
        return;
    }

    if (!servicio.getHoraSalida().equals("Pendiente")) {
        JOptionPane.showMessageDialog(this, "Este servicio ya tiene hora de salida registrada");
        return;
    }

    boolean registrado = controladorServicios.registrarSalida(idServicio);

    if (registrado) {
        JOptionPane.showMessageDialog(this, "Salida registrada correctamente");
        mostrarDatosServicio();
        mostrarTablaTiempo();
    } else {
        JOptionPane.showMessageDialog(this, "No se pudo registrar la salida");
    }
}

private void mostrarTablaTiempo() {
    modeloTabla.setRowCount(0);

    for (int i = 0; i < controladorServicios.getContadorServicios(); i++) {
        Servicio servicio = controladorServicios.obtenerServicio(i);

        Object[] fila = {
            servicio.getIdServicio(),
            servicio.getAuto().getCliente().getNombreCompleto(),
            servicio.getAuto().getMarca() + " " + servicio.getAuto().getModelo(),
            servicio.getTipoServicio(),
            servicio.getHoraEntrada(),
            servicio.getHoraSalida(),
            servicio.getDuracion()
        };

        modeloTabla.addRow(fila);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jLabel1.setText("CONTROL DEL TIEMPO");

        jLabel2.setText("Servicio:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(this::jComboBox1ActionPerformed);

        jButton1.setText("Actualizar Servicios");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jLabel3.setText("Hora Entrada ");

        jTextField2.setText("txtHoraEntrada");
        jTextField2.addActionListener(this::jTextField2ActionPerformed);

        jLabel4.setText("Hora de Salida");

        jTextField3.setText("txtHoraSalida");
        jTextField3.addActionListener(this::jTextField3ActionPerformed);

        jLabel5.setText("Duracion");

        jTextField4.setText("txtDuracion");
        jTextField4.addActionListener(this::jTextField4ActionPerformed);

        jButton2.setText("Registrar Salida");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jButton1)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel5))
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(207, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            cargarServicios();
            mostrarTablaTiempo();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            registrarSalida();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
            mostrarDatosServicio();
    }//GEN-LAST:event_jComboBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
